{application,comeonin,
             [{config_mtime,1727313624},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger]},
              {description,"A specification for password hashing libraries"},
              {modules,['Elixir.Comeonin',
                        'Elixir.Comeonin.BehaviourTestHelper',
                        'Elixir.Comeonin.PasswordHash']},
              {registered,[]},
              {vsn,"5.4.0"}]}.
